#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  labels:
#    app: web
#  name: task3
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: web
#  template:
#    metadata:
#      labels:
#        app: web
#    spec:
#      containers:
#        - image: lashtaj/task2:latest
#          name: task3
#          ports:
#            - containerPort: 80
#
#---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: web
#  name: task3
#spec:
#  ports:
#    - nodePort: 32223
#      port: 80
#      protocol: TCP
#      targetPort: 80
#  selector:
#    app: web
#  type: NodePort
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.16.1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
    - nodePort: 32223
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  type: NodePort